### ISSUE TITLE
Problem with Parallel Query Job

### ISSUE THREAD

**Issue by zerosar** [friflo/Friflo.Engine.ECS#36]
```
using Friflo.Engine.ECS;
using Friflo.Engine.ECS.Systems;

namespace TestECS;

class Program
{
    static void Main(string[] args)
    {
        ParallelJobRunner jobRunner = new ParallelJobRunner(Environment.ProcessorCount);
        EntityStore world = new EntityStore { JobRunner = jobRunner };
        SystemRoot systemRoot = new SystemRoot(world) { new TestSystem() };

        var archetype = world.GetArchetype(ComponentTypes.Get<Position>());
        archetype.CreateEntities(7993);

        systemRoot.Update(default);
        Thread.Sleep(2000);
        systemRoot.Update(default);
        
        Console.ReadKey();
    }
}

public class TestSystem : QuerySystem<Position>
{
    protected override void OnUpdate()
    {
        var queryJob = Query.ForEach((myComponents, entities) =>
        {
            for (int n = 0; n < entities.Length; n++)
            {
                myComponents[n].x += 10f;
            }
        });
        queryJob.RunParallel();
        Query.Store.JobRunner.Dispose();
    }
}
```

The second call to `systemRoot.Update(default);` causes an error if I have 7993+ entities.
It doesn't matter if I use TestSystem or implement `var queryJob` in `static void Main(string[] args)`!

Maybe I'm missing something?

```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ParallelJobRunner'.
   at Friflo.Engine.ECS.ParallelJobRunner.ExecuteJob(Object job, JobTask[] tasks)
   at Friflo.Engine.ECS.QueryJob`1.RunParallel()
   at TestECS.TestSystem.OnUpdate() in C:\projects\TestECS\TestECS\Program.cs:line 36
   at Friflo.Engine.ECS.Systems.QuerySystemBase.OnUpdateGroup()
   at Friflo.Engine.ECS.Systems.SystemGroup.OnUpdateGroup()
   at Friflo.Engine.ECS.Systems.SystemGroup.Update(UpdateTick tick)
   at TestECS.Program.Main(String[] args) in C:\projects\TestECS\TestECS\Program.cs:line 19
```

**Comment by friflo** [comment]
A `JobRunner` contains a set of worker threads.
These threads are utilized when calling `RunParallel()`.
When `RunParallel()` finishes these threads are idle and will be used again for the next `RunParallel()` cycle.

*Reason:* Reusing threads bring a significant performance boost because thread creation and disposing has a very high performance penalty.

So the usage pattern of a single `JobRunner` is
- Create a `JobRunner` when the applications starts.
- Dispose the `JobRunner` before the applications finishes.

Modified your code without testing.

```cs
using Friflo.Engine.ECS;
using Friflo.Engine.ECS.Systems;

namespace TestECS;

class Program
{
    static void Main(string[] args)
    {
        ParallelJobRunner jobRunner = new ParallelJobRunner(Environment.ProcessorCount);
        EntityStore world = new EntityStore { JobRunner = jobRunner };
        SystemRoot systemRoot = new SystemRoot(world) { new TestSystem() };

        var archetype = world.GetArchetype(ComponentTypes.Get<Position>());
        archetype.CreateEntities(7993);

        systemRoot.Update(default);
        Thread.Sleep(2000);
        systemRoot.Update(default);
        jobRunner.Dispose(); // jobRunner is not used anymore so it can be disposed
        
        Console.ReadKey();
    }
}

public class TestSystem : QuerySystem<Position>
{
    protected override void OnUpdate()
    {
        var queryJob = Query.ForEach((myComponents, entities) =>
        {
            for (int n = 0; n < entities.Length; n++)
            {
                myComponents[n].x += 10f;
            }
        });
        queryJob.RunParallel();
        // Query.Store.JobRunner.Dispose(); doing this stop all worker threads
    }
}
```

**Comment by zerosar** [comment]
Got it. Thanks for the explanation.
